Repository T-BluePot/barogagi-front, pull requests merged in 2025-07, with the labels that each got.

#10 [DESIGN] 모달 컴포넌트 작업(일반 알림 모달)
  src/components/layout/CommonAlertModalLayout.tsx
  src/components/layout/CommonConfirmModalLayout.tsx
  src/components/modal/CommonAlertModal.tsx
  src/components/modal/CommonConfirmModal.tsx
  src/components/modal/CommonModalContent.tsx
  src/pages/auth/AuthLandingPage.tsx
  src/types/modalTypes.ts
Labels: enhancement, design

#12 [DESIGN] auth signup pages 로직 디자인 구현
  package-lock.json
  package.json
  src/components/auth/common/CheckBoxButton.stories.ts
  src/components/auth/common/CheckBoxButton.tsx
  src/components/auth/common/CommonInput.tsx
  src/components/auth/common/PageTitle.tsx
  src/components/auth/signup/ProfileLayout.tsx
  src/components/auth/signup/SelectAllConsentButton.tsx
  src/components/auth/signup/SelectBirthBottomModal.tsx
  src/components/auth/signup/SelectGenderBottomModal.tsx
  src/components/auth/signup/SkipProfileModal.tsx
  src/components/auth/signup/TermsConsentItem.tsx
  src/components/auth/signup/TermsListSection.tsx
  src/components/common/BirthdayPicker.tsx
  src/components/common/bottom-modal/BottomModalListButton.tsx
  src/constants/texts/auth/signup/complete.ts
  src/constants/texts/auth/signup/credentials.ts
  src/constants/texts/auth/signup/profile.ts
  src/constants/texts/auth/signup/terms.ts
  src/constants/texts/auth/signup/verify.ts
  src/pages/auth/signup/CredentialsPage.tsx
  src/pages/auth/signup/ProfilePage.tsx
  src/pages/auth/signup/SignupCompletePage.tsx
  src/pages/auth/signup/TermsPage.tsx
  src/pages/auth/signup/VerifyCodePage.tsx
  src/pages/auth/signup/VerifyPhonePage.tsx
  src/routes/AuthRoutes.tsx
  src/types/auth/gender.ts
  src/types/profileTypes.ts
  src/types/termsTypes.ts
  src/utils/authSchema.ts
  src/utils/safeBack.ts
  src/utils/useBlockBackNavigation.ts
Labels: chore, design

#14 [DESIGN] 캘린터 컴포넌트 생성
  package-lock.json
  package.json
  src/components/DevNav.tsx
  src/components/main/plan/Calendar.tsx
  src/components/main/plan/calendar.css
  src/constants/texts/main/plan/selectDate.ts
  src/main.tsx
  src/mock/schedules.ts
  src/pages/main/plan/SelectDatePage.tsx
  src/routes/AuthRoutes.tsx
  src/types/schedule.ts
  src/utils/date.ts
  src/utils/getMarkedDates.ts
Labels: design
